name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v3
      with:
        token: ${{ secrets.TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id 4756703682
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}