name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v3
      with:
        token: ${{ secrets.TOKEN }}
        allow-external-github-orgs: true

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: rojo upload --api_key "$API_KEY" --universe_id 7672663738 -v --asset_id 107505894422783
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
        API_KEY: ${{ secrets.API_KEY }}