name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v3
      with:
        token: ${{ secrets.TOKEN }}
        allow-external-github-orgs: true

    - name: Report tool versions
      run: rojo --version

    - name: Generate version.lua
      run: |
        VERSION=$(jq -r .version package.json)
        echo "return {" > src/shared/version.lua
        echo "  version = '${VERSION}'," >> src/sharedversion.lua
        echo "  commit = '$(git rev-parse --short=8 HEAD)'," >> src/shared/version.lua
        echo "  branch = '${GITHUB_REF##*/}'," >> src/shared/version.lua
        echo "}" >> src/shared/version.lua

    - name: Deploy
      run: rojo upload --api_key "$API_KEY" --universe_id 7672663738 -v --asset_id 107505894422783
      env:
        API_KEY: ${{ secrets.API_KEY }}