name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Rojo version
    run: rojo --version

    - name: Deploy 
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id 4756703682
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
